apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flask-app

bases:
- ../../base

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: flask-api
    spec:
      replicas: 5
      template:
        spec:
          containers:
          - name: flask
            resources:
              requests:
                cpu: 200m
                memory: 256Mi
              limits:
                cpu: 1000m
                memory: 1Gi
  target:
    kind: Deployment
    name: flask-api

commonLabels:
  environment: prod